apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{ .Values.productShortName }}.service: api
  name: api
spec:
  replicas: {{ .Values.deployment.api.replicas | default "1" }}
  template:
    metadata:
      labels:
        {{ .Values.productShortName }}.service: api
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: api
        args:
        - bin/uwsgi
        image: {{ .Values.image.registry }}/api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.deployment.api.resources.requests.memory | default "700Mi" }}
            cpu: {{ .Values.deployment.api.resources.requests.cpu | default "500m" }}
          limits:
            memory: {{ .Values.deployment.api.resources.limits.memory | default "1500Mi" }}
            cpu: {{ .Values.deployment.api.resources.limits.cpu | default "2000m" }}
        volumeMounts:
        - name: {{ .Values.productShortName }}-config
          mountPath: /etc/{{ .Values.productShortName }}/settings/settings.py
          subPath: settings.py
      volumes:
      - name: {{ .Values.productShortName }}-config
        configMap:
          name: {{ .Values.productShortName }}
