apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.productShortName }}.service: elements
  name: elements
spec:
  ports:
  - port: 80
  selector:
    {{ .Values.productShortName }}.service: elements
