apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{ .Values.productShortName }}.service: elements
  name: elements
spec:
  replicas: {{ .Values.deployment.elements.replicas | default "1" }}
  template:
    metadata:
      labels:
        {{ .Values.productShortName }}.service: elements
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: elements
        args:
        - nginx
        image: {{ .Values.image.registry }}/elements:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.deployment.elements.resources.requests.memory | default "30Mi" }}
            cpu: {{ .Values.deployment.elements.resources.requests.cpu | default "10m" }}
          limits:
            memory: {{ .Values.deployment.elements.resources.limits.memory | default "50Mi" }}
            cpu: {{ .Values.deployment.elements.resources.limits.cpu | default "100m" }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
