{{ if and (eq .Values.influxdb.host "influxdb") (eq (toString .Values.influxdb.port) "8086") -}}
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    {{ .Values.productShortName }}.service: influxdb
spec:
  ports:
    - name: default
      port: 8086
    - name: backup
      port: 8088
  selector:
    {{ .Values.productShortName }}.service: influxdb
{{- end }}
