kind: Service
apiVersion: v1
metadata:
  name: insights-handler
  labels:
    {{ .Values.productShortName }}.service: insights-handler
spec:
  ports:
    - port: 80
  selector:
    {{ .Values.productShortName }}.service: insights-handler
