apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{ .Values.productShortName }}.service: logstash
  name: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{ .Values.productShortName }}.service: logstash
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 8 }}
      containers:
      - name: logstash
        env:
        - name: ELASTIC_URI
          value: http{{ if .Values.elasticsearch.tls }}s{{end}}://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}
        - name: ELASTIC_USERNAME
          value: {{ .Values.elasticsearch.username | default "admin" }}
        - name: ELASTIC_PASSWORD
          value: {{ .Values.elasticsearch.password | default "admin" }}
        image: {{ .Values.image.registry }}/logstash:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            memory: 500Mi
            cpu: 170m
          limits:
            memory: 700Mi
            cpu: 1000m
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
