apiVersion: v1
kind: Service
metadata:
  labels:
    {{ .Values.productShortName }}.service: manage
  name: manage
spec:
  ports:
  - port: 80
  selector:
    {{ .Values.productShortName }}.service: manage
