apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dockerSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerSecret.dockerconfigjson }}