apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-elements
  labels:
    app: elements
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 80
  selector:
    app: elements
    release: {{ .Release.Name }}
