{{ if eq .Values.fdb.host "" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-fdb
  labels:
    app: fdb
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: 4500
  selector:
    app: fdb
    release: {{ .Release.Name }}
{{- end }}
