apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-huproxy
  labels:
    app: huproxy
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 8086
  selector:
    app: huproxy
    release: {{ .Release.Name }}
