apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-memcached
  labels:
    app: memcached
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: memcached
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: memcached
        image: {{ include "get.image.name" (dict "name" "memcached" "globals" .Values.global) }}
        resources:
          requests:
            memory: 30Mi
            cpu: 1m
          limits:
            memory: 60Mi
            cpu: 100m
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
