[[http]]
name = "all_backends"
bind-addr = "0.0.0.0:9096"
output = [
    { name="influxdb", location="http://influxdb:8086/write", type="influxdb", fail-on-error=false},
    { name="fdb", location="fdb:4500", type="fdb", fail-on-error=false},
]


# metering will send stats for samples/org/machine
# you have to also set amqp-url for metering to work
enable-metering = true

amqp-url = "amqp://guest:guest@rabbitmq:5672/"

cron-schedule = "@every 10s"

# drop-unauthorized is used when data are coming to gocky having a source
# different than traefik (e.g. unauthorized)
# if drop-unauthorized is true, then gocky will return forbidden error
# if set to false, it will write data to graphite in the form of
# Unauthorized_machineID.cpu.0.idle


#drop-unauthorized = true
