dependencies:
  - alias: rabbitmq
    condition: rabbitmq.enabled
    repository: https://charts.bitnami.com/bitnami
    name: rabbitmq
    version: 8.0.5
  - alias: mongodb
    condition: eq .Values.mongodb.host ""
    repository: https://charts.bitnami.com/bitnami
    name: mongodb
    version: 10.0.5
